# Generated by Django 5.0.3 on 2024-07-12 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_comments_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 15, 35, 8, 321682)),
        ),
    ]
