# Generated by Django 5.0.3 on 2024-07-24 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camps',
            fields=[
                ('camp_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('camp_name', models.CharField(max_length=100)),
                ('camp_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('meet_link', models.URLField(blank=True)),
                ('camp_theme', models.CharField(max_length=20)),
                ('no_of_registered_user', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camp_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.camps')),
            ],
        ),
        migrations.CreateModel(
            name='Camp_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_files', models.FileField(upload_to='camps')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='camps.camps')),
            ],
        ),
    ]
