# Generated by Django 5.0.3 on 2024-07-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camps',
            name='date',
        ),
    ]
