# Generated by Django 5.0.3 on 2024-07-24 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_remove_camps_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='camps',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 15, 14, 24, 343185)),
        ),
    ]
