# Generated by Django 5.0.3 on 2024-07-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_camps_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camps',
            name='created_at',
        ),
    ]
