# Generated by Django 5.0.1 on 2024-06-05 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='BookmarkPost',
        ),
    ]
