# Generated by Django 5.0.1 on 2024-06-05 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_bookmark_bookmarkpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('com_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=100)),
                ('com_description', models.CharField(max_length=400)),
                ('com_followers', models.IntegerField(default=0)),
                ('com_image', models.ImageField(upload_to='com_images')),
            ],
        ),
    ]
