# Generated by Django 5.0.1 on 2024-06-20 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_community_com_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkpost',
            name='bookmark_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='com_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Camps',
            fields=[
                ('camp_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('camp_name', models.CharField(max_length=100)),
                ('camp_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=200)),
                ('meet_link', models.URLField(blank=True)),
                ('camp_theme', models.CharField(max_length=20)),
                ('no_of_registered_user', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camp_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.camps')),
            ],
        ),
        migrations.CreateModel(
            name='Camp_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_files', models.FileField(upload_to='camp_files')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.camps')),
            ],
        ),
    ]
