# Generated by Django 5.0.3 on 2024-07-07 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_bookmarkpost_bookmark_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
