# Generated by Django 5.0.3 on 2024-07-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_post_upload_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-upload_time']},
        ),
    ]
